(use-package which-key
  :ensure t
  :config
  (which-key-mode 1))

(use-package general
  :ensure t
  :after evil
  :config
  (general-evil-setup)

  (general-create-definer leader
    :prefix "SPC"
    :global-prefix "C-SPC")

  (leader
    :keymaps 'override
    "k" '(delete-window :which-key "delete window")
    "." '(counsel-find-file :which-key "find file")
    "SPC" '(counsel-M-x :which-key "M-x")
    ";" '(counsel-imenu :which-key "imenu")
    "'" '(projectile-switch-project :which-key "projectile")
    "a a" '(ace-window :which-key "ace window")
    "a d" '(ace-delete-window :which-key "ace delete window")
    "b b" '(ivy-switch-buffer :which-key "switch buffer")
    "b d" '(kill-current-buffer :which-key "kill current buffer")
    "b k" '(kill-buffer :which-key "kill buffer")
    "b m" '(bookmark-jump :which-key "bookmarks")
    "c c" '(compile :which-key "compile")
    "c r" '(recompile :which-key "recompile")
    "d d" '(dired :which-key "dired")
    "d j" '(dired-jump :which-key "dired jump")
    "e e" '(eval-last-sexp :which-key "eval last sexp")
    "e b" '(eval-buffer :which-key "eval buffer")
    "f f" '(counsel-find-file :which-key "find file")
    "f r" '(counsel-recentf :which-key "recent files")
    "f s" '(save-buffer :which-key "save buffer")
    "F f" '(make-frame :which-key "new frame")
    "F d" '(delete-frame :which-key "delete frame")
    "g s" '(magit-status :which-key "magit status")
    "g l" '(magit-log :which-key "magit log")
    "h h" '(help :which-key "help")
    "h f" '(counsel-describe-function :which-key "describe function")
    "h v" '(counsel-describe-variable :which-key "describe variable")
    "i s" '(yas-insert-snippet :which-key "insert snippet")
    "i n" '(yas-new-snippet :which-key "new snippet")
    "o a" '(org-agenda :which-key "org agenda")
    "o c" '(org-capture :which-key "org capture")
    "o l" '(org-store-link :which-key "org store link")
    "p p" '(projectile-switch-project :which-key "switch project")
    "p f" '(projectile-find-file :which-key "find file in project")
    "r r" '(query-replace-regexp :which-key "replace regexp")
    "r y" '(yank-from-register :which-key "yank from register")
    "r j" '(jump-to-register :which-key "jump to register")
    "s r" '(counsel-rg :which-key "ripgrep")
    "s g" '(counsel-git-grep :which-key "git grep")
    "s s" '(swiper :which-key "swiper")
    "T" '(counsel-load-theme :which-key "load theme")
    "t t" '(toggle-truncate-lines :which-key "truncate lines")
    "t n" '(display-line-numbers-mode :which-key "line numbers")
    "t h" '(hl-line-mode :which-key "highlight line")
    "t w" '(whitespace-mode :which-key "whitespace")
    "t s" '(flyspell-mode :which-key "spell check")
    "t r" '(visual-line-mode :which-key "visual line wrap")
    "w v" '(split-window-right :which-key "split right")
    "w s" '(split-window-below :which-key "split below")
    "w d" '(delete-window :which-key "delete window")
    "w m" '(delete-other-windows :which-key "maximize window")
    "w o" '(delete-other-windows :which-key "delete other windows")
    "w h" '(evil-window-left :which-key "window left")
    "w j" '(evil-window-down :which-key "window down")
    "w k" '(evil-window-up :which-key "window up")
    "w l" '(evil-window-right :which-key "window right")
    "w H" '(evil-window-move-far-left :which-key "move window left")
    "w J" '(evil-window-move-far-down :which-key "move window down")
    "w K" '(evil-window-move-far-up :which-key "move window up")
    "w L" '(evil-window-move-far-right :which-key "move window right")
    "w u" '(winner-undo :which-key "winner undo")
    "w C-r" '(winner-redo :which-key "winner redo")
    "w w" '(other-window :which-key "other window")
    "x a" '(align :which-key "align")
    "q q" '(save-buffers-kill-terminal :which-key "quit emacs")))

(provide 'init-keybindings)
