[window]
startup_mode = "Maximized"
decorations = "none"
opacity = 0.9
blur = true

[font]
normal = {family = "Hack Nerd Font", style = "Regular"}
size = 10

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 600
blink_timeout = 0

# Настройки выделения текста и буфера обмена
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t" 
save_to_clipboard = true # Автоматически копирует выделенное

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]

[mouse]
hide_when_typing = true

[keyboard]
bindings = [

    { key = "C", mods = "Control|Shift", action = "Copy" },

    # Paste from clipboard (Ctrl + Shift + V)
    { key = "V", mods = "Control|Shift", action = "Paste" },

    # Quit Alacritty (Ctrl + Shift + Q)
    { key = "Q", mods = "Control|Shift", action = "Quit" },

    # Open a new window (Ctrl + Shift + N)
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },

    # Toggle fullscreen (F11)
    { key = "F11", action = "ToggleFullscreen" },

    # Scroll up (Ctrl + Shift + Up Arrow)
    { key = "Up", mods = "Control|Shift", action = "ScrollPageUp" },

    # Scroll down (Ctrl + Shift + Down Arrow)
    { key = "Down", mods = "Control|Shift", action = "ScrollPageDown" },
 
    # Increase Font Size (Ctrl + Plus)
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },

    # Decrease Font Size (Ctrl + Minus)
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" }
]
