[window]
decorations = "Transparent"
opacity = 0.80

[font]
normal = {family = "Hack Nerd Font", style = "Regular"}
size = 8

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 600
blink_timeout = 0